"use client";

import * as React from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, FileWarning, ShieldCheck } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { Badge, type BadgeProps } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { applySimulatedDecision, canSimulateDecision, requiresSimulatedStepUp, type SimulatedDecision } from "../approval-prototype-controller";
import type { ApprovalRecord, ApprovalRisk, ApprovalState } from "../approval-data";

const stateVariant = (state: ApprovalState): BadgeProps["variant"] => state === "Approved" ? "success" : state === "Rejected" || state === "Expired" ? "error" : state === "Blocked" || state === "Clarification requested" ? "warning" : "brand";
const riskVariant = (risk: ApprovalRisk): BadgeProps["variant"] => risk === "Critical" ? "error" : risk === "High" ? "warning" : risk === "Medium" ? "brand" : "neutral";
const returnPath = () => typeof window === "undefined" ? "/approvals?view=queue" : new URLSearchParams(window.location.search).get("from")?.startsWith("/approvals") ? new URLSearchParams(window.location.search).get("from")! : "/approvals?view=queue";

export function ApprovalDetailWorkspace({ approval, presentationState = "ready" }: { approval?: ApprovalRecord; presentationState?: "ready" | "loading" | "error" }) {
  const [current, setCurrent] = React.useState(approval);
  const [decision, setDecision] = React.useState<SimulatedDecision | null>(null);
  const [reason, setReason] = React.useState("");
  const [reasonError, setReasonError] = React.useState("");
  const [stepUp, setStepUp] = React.useState(false);
  const back = React.useMemo(() => returnPath(), []);
  if (presentationState === "loading") return <div className="grid gap-4"><Skeleton className="h-12 w-1/3" /><Skeleton className="h-80 w-full" /></div>;
  if (presentationState === "error" || !current) return <Card className="border-error-border bg-error-bg"><CardContent className="p-6"><h1 className="text-lg font-semibold text-error">Approval unavailable</h1><p className="mt-2 text-sm text-error">This fictional approval cannot be displayed. No real approval service was contacted.</p><Button asChild className="mt-4" variant="secondary"><Link href="/approvals?view=queue">Return to Queue</Link></Button></CardContent></Card>;
  const actionable = ["Pending", "Clarification requested", "Blocked"].includes(current.state);
  const approveAvailable = canSimulateDecision(current, "approve");
  const stepUpRequired = requiresSimulatedStepUp(current);
  const decisionLabel = decision === "approve" ? "approval" : decision === "reject" ? "rejection" : "clarification request";
  const confirm = () => { if (!decision) return; if (decision === "reject" && !reason.trim()) return setReasonError("A reason is required to simulate rejection."); if (stepUpRequired && !stepUp) return; setCurrent(applySimulatedDecision(current, decision, reason)); setDecision(null); setReason(""); };
  const open = (next: SimulatedDecision) => { setDecision(next); setReasonError(""); setStepUp(false); };
  return <div className="flex min-w-0 flex-col gap-8">
    <PageHeader title="Approval detail" description="Inspect the exact fictional action, evidence, and policy rationale before using a simulated decision." icon={ShieldCheck} actions={<div className="flex flex-wrap items-center gap-2"><Button asChild variant="ghost"><Link href={back}><ArrowLeft className="size-4" aria-hidden="true" />Return to Queue</Link></Button><Badge variant={riskVariant(current.risk)}>{current.risk} risk</Badge><Badge variant={stateVariant(current.state)}>{current.state}</Badge></div>} />
    <Notice />
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]">
      <aside className="order-1 grid content-start gap-4 xl:order-2"><Card className="border-brand shadow-atlas-md"><CardHeader className="border-b border-border-default bg-surface-secondary"><CardTitle>Simulated decision</CardTitle><CardDescription>Controls change only this local screen state for the current session.</CardDescription></CardHeader><CardContent className="grid gap-3 pt-4 sm:pt-6"><Button onClick={() => open("approve")} disabled={!actionable || !approveAvailable}>Simulate approval</Button><Button variant="destructive" onClick={() => open("reject")} disabled={!actionable}>Simulate rejection</Button><Button variant="secondary" onClick={() => open("request-clarification")} disabled={!actionable}>Simulate clarification request</Button>{!approveAvailable && <p role="status" className="text-sm text-error">Approval unavailable: complete the required fictional evidence before approving.</p>}{!actionable && <p className="text-sm text-foreground-secondary">This approval is historical or no longer actionable in the prototype.</p>}</CardContent></Card><InfoCard title="Request context"><Details items={{ Agent: <Link className="text-brand hover:underline" href={`/agents/${current.agent.id}`}>{current.agent.name}</Link>, Run: `${current.runId} (unavailable in prototype)`, Requested: new Date(current.requestedAt).toLocaleString(), Expires: current.expiresAt ? new Date(current.expiresAt).toLocaleString() : "Not applicable", "Execution outcome": current.executionOutcome }} /></InfoCard>{current.executionOutcome === "Indeterminate" && <Card className="border-warning-border bg-warning-bg"><CardContent className="p-4"><h2 className="font-semibold text-warning">Indeterminate outcome</h2><p className="mt-1 text-sm text-foreground">This historical fixture is unresolved locally. No real reconciliation occurred.</p></CardContent></Card>}</aside>
      <div className="order-2 grid gap-6 xl:order-1"><InfoCard title="Proposed action" description="The exact fictional action being reviewed."><Details items={{ Action: current.action, Target: current.target, Consequence: current.consequence, "Affected scope": current.scope }} /></InfoCard><InfoCard title="Policy and governance rationale" description="Why an operator review is required."><Details items={{ "Governing policy": current.policy, "Review rationale": current.policyReason }} /></InfoCard><InfoCard title="Evidence and context" description="External material is separated from system metadata."><div className="grid gap-4"><div className="rounded-atlas-md border border-border-default bg-surface-secondary p-4"><Details items={{ "Evidence source": current.evidence.source, Provenance: current.evidence.provenance }} /></div><div className="rounded-atlas-md border border-warning-border bg-warning-bg p-4"><p className="text-xs font-semibold uppercase tracking-wide text-warning">Untrusted evidence preview</p><p className="mt-2 text-sm leading-relaxed text-foreground">{current.evidence.preview}</p></div>{!current.evidence.complete && <div className="rounded-atlas-md border border-error-border bg-error-bg p-4"><div className="flex gap-2"><FileWarning className="mt-0.5 size-4 shrink-0 text-error" aria-hidden="true" /><div><h3 className="font-semibold text-error">Approval unavailable</h3><p className="mt-1 text-sm text-error">Missing fictional evidence: {current.evidence.missing?.join(", ")}.</p></div></div></div>}</div></InfoCard><InfoCard title="Activity" description="Local prototype activity is explicitly labeled."><ol className="grid gap-4 border-l border-border-default pl-5">{current.activity.map((item, index) => <li key={`${item.at}-${index}`} className="relative"><span className="absolute -left-[1.75rem] top-1.5 size-2.5 rounded-full border-2 border-surface bg-brand" /><div className="flex gap-2"><p className="text-sm font-medium text-foreground">{item.actor}</p>{item.simulated && <Badge variant="neutral">Simulated</Badge>}</div><p className="mt-1 text-sm text-foreground-secondary">{item.detail}</p><time className="text-xs text-foreground-tertiary">{item.at}</time></li>)}</ol></InfoCard></div>
    </section>
    <Dialog open={decision !== null} onOpenChange={(isOpen) => { if (!isOpen) setDecision(null); }}><DialogContent><DialogHeader><DialogTitle>Simulate {decisionLabel}</DialogTitle><DialogDescription>This changes only the local fixture in this browser session. It will not authorize, execute, record, or persist anything.</DialogDescription></DialogHeader>{decision && <div className="grid gap-4"><div className="rounded-atlas-md border border-border-default bg-surface-secondary p-3 text-sm"><p className="font-medium text-foreground">{current.id}</p><p className="mt-1 text-foreground-secondary">{current.action}</p></div><label className="grid gap-1 text-sm font-medium text-foreground">Reason {decision === "reject" ? "(required)" : "(optional)"}<textarea value={reason} onChange={(event) => { setReason(event.target.value); setReasonError(""); }} aria-invalid={Boolean(reasonError)} className="min-h-24 rounded-atlas-md border border-border-default bg-surface px-3 py-2 text-sm font-normal" /></label>{reasonError && <p role="alert" className="text-sm text-error">{reasonError}</p>}{stepUpRequired && <label className="flex gap-3 rounded-atlas-md border border-warning-border bg-warning-bg p-3 text-sm"><input aria-label="Simulated step-up confirmation" type="checkbox" checked={stepUp} onChange={(event) => setStepUp(event.target.checked)} className="mt-1 size-4" /><span><strong>Simulated step-up confirmation.</strong> This does not authenticate you or affect a real system.</span></label>}</div>}<DialogFooter><Button variant="secondary" onClick={() => setDecision(null)}>Cancel</Button><Button variant={decision === "reject" ? "destructive" : "primary"} onClick={confirm} disabled={stepUpRequired && !stepUp}>Confirm simulated {decisionLabel}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Notice() { return <Card className="border-info-border bg-info-bg"><CardContent className="flex gap-3 p-4 text-sm leading-relaxed text-info"><AlertTriangle className="mt-0.5 size-4 shrink-0" aria-hidden="true" /><p><strong>Frontend prototype.</strong> Any decision is a session-only local simulation. It does not affect a real agent, runtime, service, policy engine, audit system, or persisted record.</p></CardContent></Card>; }
function InfoCard({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle>{description && <CardDescription>{description}</CardDescription>}</CardHeader><CardContent>{children}</CardContent></Card>; }
function Details({ items }: { items: Record<string, React.ReactNode> }) { return <dl className="grid gap-4 sm:grid-cols-2">{Object.entries(items).map(([label, value]) => <div key={label} className="grid gap-1"><dt className="text-[11px] font-semibold uppercase tracking-wide text-foreground-tertiary">{label}</dt><dd className="text-sm leading-relaxed text-foreground">{value}</dd></div>)}</dl>; }
